<?php

namespace App\Enums;

enum ErrorCode: string
{
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case FORBIDDEN_ACTION = 'FORBIDDEN_ACTION';
    case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    case CONFLICT = 'CONFLICT';
    case INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION';
    case BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
}
